- name: clone {{repo_name}}
  git: >
    repo=https://github.com/NordicSemiconductor/{{repo_name}}.git
    dest={{repo_dir}}

- name: set cmake boost root
  command: chdir={{repo_dir}} npm config set cmake_BOOST_ROOT={{boost_root}}

- name: install npm packages for {{repo_name}}
  command: chdir={{repo_dir}} npm install
